export const STORAGE_KEYS = {
  USER: 'sobagi-user',
  EXPENSES: 'sobagi-expenses',
  LAST_EMOTION: 'sobagi-last-emotion',
  MAILBOX_READ_IDS: 'sobagi-mailbox-read-ids',
  FOUND_ITEM_IDS: 'sobagi-found-item-ids',
  PENDING_NEW_ITEM_ID: 'sobagi-pending-item-id',
  LAST_ITEM_DATE: 'sobagi-last-item-date',
  STAGED_ITEM_ID: 'sobagi-staged-item-id',
  LAST_VISIT_DATE: 'sobagi-last-visit-date',
  OBSERVATION_SAVE_COUNT: 'sobagi-observation-save-count',
  MAILBOX_DELIVERED_IDS: 'sobagi-mailbox-delivered-ids',
  LAST_BAG_OPEN_DAYS: 'sobagi-last-bag-open-days',
  ROOM_PLACEMENTS: 'sobagi-room-placements',
  PENDING_PLACEMENT: 'sobagi-pending-placement',
  CATEGORY_MIGRATION_DONE: 'sobagi-category-migration-done',
  PEBBLE_COUNT: 'sobagi-pebble-count',
  RESTS_TODAY: 'sobagi-rests-today',
  LAST_REST_DATE: 'sobagi-last-rest-date',
  LAST_REST_AT: 'sobagi-last-rest-at',
  KEPT_ITEM_IDS: 'sobagi-kept-item-ids',
  DISCOVERY_QUEUE: 'sobagi-discovery-queue',
  DISCOVERY_MIGRATION_DONE: 'sobagi-discovery-migration-done',
} as const;
